/**
 * DEPRECATED — seeding now happens in Supabase via SQL migrations.
 *
 * Auth users are created in Supabase Auth (auth.users) and their profiles are
 * generated by the `on_auth_user_created` trigger. The catalog/events/tickets
 * are seeded by the `seed_*` migrations applied to the Supabase project.
 *
 * Do NOT run `prisma db seed` against Supabase — it would create users without
 * Supabase Auth accounts and collide with existing rows.
 *
 * See docs/SUPABASE.md for the full schema, connection info and seed details.
 */
console.log(
  "Seeding is handled by Supabase migrations. See docs/SUPABASE.md. Nothing to do."
);
