import type { SeatLayoutDocument } from "../types";

/** Simplified BMICH - main hall with side tiers. */
export const BMICH_LAYOUT: SeatLayoutDocument = {
  version: 1,
  name: "BMICH Main Hall",
  viewBox: { width: 1000, height: 760 },
  orientation: "FRONT",
  landmarks: [
    { id: "stage", type: "STAGE_BOX", label: "Stage", x: 300, y: 20, width: 400, height: 88 },
    { id: "screen", type: "SCREEN", label: "Projection", x: 340, y: 120, width: 320, height: 10 },
  ],
  categories: [
    { id: "platinum", name: "Platinum", color: "#f59e0b", price: 600000, enabled: true, sortOrder: 0 },
    { id: "gold", name: "Gold", color: "#eab308", price: 350000, enabled: true, sortOrder: 1 },
    { id: "silver", name: "Silver", color: "#64748b", price: 200000, enabled: true, sortOrder: 2 },
    { id: "tier", name: "Side Tier", color: "#14b8a6", price: 120000, enabled: true, sortOrder: 3 },
  ],
  naming: { rowScheme: "LETTERS", colScheme: "NUMBERS", separator: "" },
  sections: [
    {
      id: "front-platinum",
      name: "Front Platinum",
      enabled: true,
      kind: "GRID",
      categoryId: "platinum",
      x: 340,
      y: 160,
      rows: 5,
      cols: 14,
      rowGap: 6,
      colGap: 6,
      seatWidth: 26,
      seatHeight: 26,
    },
    {
      id: "center-gold",
      name: "Center Gold",
      enabled: true,
      kind: "GRID",
      categoryId: "gold",
      x: 280,
      y: 320,
      rows: 8,
      cols: 18,
      rowGap: 5,
      colGap: 5,
      seatWidth: 22,
      seatHeight: 22,
    },
    {
      id: "rear-silver",
      name: "Rear Silver",
      enabled: true,
      kind: "GRID",
      categoryId: "silver",
      x: 220,
      y: 520,
      rows: 6,
      cols: 22,
      rowGap: 4,
      colGap: 4,
      seatWidth: 18,
      seatHeight: 18,
    },
    {
      id: "tier-left",
      name: "Left Tier",
      enabled: true,
      kind: "GRID",
      categoryId: "tier",
      x: 60,
      y: 200,
      rows: 10,
      cols: 5,
      rowGap: 4,
      colGap: 4,
      seatWidth: 18,
      seatHeight: 18,
    },
    {
      id: "tier-right",
      name: "Right Tier",
      enabled: true,
      kind: "GRID",
      categoryId: "tier",
      x: 820,
      y: 200,
      rows: 10,
      cols: 5,
      rowGap: 4,
      colGap: 4,
      seatWidth: 18,
      seatHeight: 18,
    },
  ],
};
