import type { SeatLayoutDocument } from "../types";

/** Simplified Nelum Pokuna Theatre - orchestra + balcony blocks facing stage. */
export const NELUM_POKUNA_LAYOUT: SeatLayoutDocument = {
  version: 1,
  name: "Nelum Pokuna Theatre",
  viewBox: { width: 960, height: 720 },
  orientation: "FRONT",
  landmarks: [
    { id: "stage", type: "STAGE_BOX", label: "Stage", x: 280, y: 24, width: 400, height: 72 },
    { id: "screen", type: "SCREEN", label: "Screen", x: 320, y: 108, width: 320, height: 12 },
  ],
  categories: [
    { id: "vip", name: "VIP", color: "#eab308", price: 750000, enabled: true, sortOrder: 0 },
    { id: "premium", name: "Premium", color: "#06b6d4", price: 450000, enabled: true, sortOrder: 1 },
    { id: "standard", name: "Standard", color: "#3b82f6", price: 250000, enabled: true, sortOrder: 2 },
    { id: "balcony", name: "Balcony", color: "#06b6d4", price: 150000, enabled: true, sortOrder: 3 },
  ],
  naming: { rowScheme: "LETTERS", colScheme: "NUMBERS", separator: "" },
  sections: [
    {
      id: "orch-vip",
      name: "Orchestra VIP",
      enabled: true,
      kind: "GRID",
      categoryId: "vip",
      x: 320,
      y: 160,
      rows: 4,
      cols: 12,
      rowGap: 6,
      colGap: 6,
      seatWidth: 28,
      seatHeight: 28,
    },
    {
      id: "orch-premium",
      name: "Orchestra Premium",
      enabled: true,
      kind: "GRID",
      categoryId: "premium",
      x: 280,
      y: 300,
      rows: 6,
      cols: 16,
      rowGap: 5,
      colGap: 5,
      seatWidth: 24,
      seatHeight: 24,
    },
    {
      id: "orch-standard",
      name: "Orchestra Standard",
      enabled: true,
      kind: "GRID",
      categoryId: "standard",
      x: 240,
      y: 460,
      rows: 5,
      cols: 20,
      rowGap: 4,
      colGap: 4,
      seatWidth: 20,
      seatHeight: 20,
    },
    {
      id: "balcony-left",
      name: "Balcony Left",
      enabled: true,
      kind: "GRID",
      categoryId: "balcony",
      x: 80,
      y: 180,
      rows: 8,
      cols: 6,
      rowGap: 4,
      colGap: 4,
      seatWidth: 18,
      seatHeight: 18,
    },
    {
      id: "balcony-right",
      name: "Balcony Right",
      enabled: true,
      kind: "GRID",
      categoryId: "balcony",
      x: 760,
      y: 180,
      rows: 8,
      cols: 6,
      rowGap: 4,
      colGap: 4,
      seatWidth: 18,
      seatHeight: 18,
    },
  ],
};
